package ticket

import (
	"context"
	"errors"
	"fmt"
	"io"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/google/uuid"
	domainTicket "github.com/trickreport/backend/internal/domain/ticket"
)

// AttachmentRepository is the port for attachment persistence.
type AttachmentRepository interface {
	Create(ctx context.Context, input AttachmentUploadInput) (*domainTicket.Attachment, error)
	List(ctx context.Context, ticketID uuid.UUID) ([]domainTicket.Attachment, error)
	GetByID(ctx context.Context, id, ticketID uuid.UUID) (*domainTicket.Attachment, []byte, error)
}

// AttachmentUploadInput holds the data for storing an attachment at the repo level.
type AttachmentUploadInput struct {
	TicketID    uuid.UUID
	UserID      uuid.UUID
	Filename    string
	ContentType string
	FileSize    int64
	FileData    []byte
}

// AttachmentConfig holds configuration for the attachment service.
type AttachmentConfig struct {
	MaxFileSize int64 // default: 10 MB (10 << 20)
}

// DefaultAttachmentConfig returns the default attachment configuration.
func DefaultAttachmentConfig() AttachmentConfig {
	return AttachmentConfig{
		MaxFileSize: 10 << 20, // 10 MB
	}
}

// File validation errors.
var (
	ErrFileTooLarge   = errors.New("file size exceeds the maximum allowed limit")
	ErrInvalidContent = errors.New("file content type is not allowed or does not match declared type")
	ErrEmptyFilename  = errors.New("filename cannot be empty")
)

// allowedContentTypes is the whitelist of accepted MIME types for uploads.
var allowedContentTypes = map[string]bool{
	"image/jpeg":      true,
	"image/png":       true,
	"image/gif":       true,
	"image/webp":      true,
	"image/bmp":       true,
	"application/pdf": true,
	"text/plain":      true,
	"text/csv":        true,
	"application/msword":                                                        true,
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document":   true,
	"application/vnd.ms-excel":                                                  true,
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":         true,
	"application/vnd.openxmlformats-officedocument.presentationml.presentation": true,
	"application/zip": true,
}

// specialCharRegex matches characters that are unsafe in filenames.
var specialCharRegex = regexp.MustCompile(`[^\w.\-]`)

// multiUnderscoreRegex collapses multiple consecutive underscores.
var multiUnderscoreRegex = regexp.MustCompile(`_+`)

// AttachmentService handles file attachment operations.
//
// TODO(fase-12): inject a storage.Storage implementation so file bytes are
// streamed to/from an object backend (local disk or S3) instead of being held
// in memory via AttachmentRepository. Do NOT edit this file as part of the
// storage stub — wire it in a follow-up change.
type AttachmentService struct {
	attachments AttachmentRepository
	tickets     Repository
	cfg         AttachmentConfig
}

// NewAttachmentService creates a new AttachmentService with default config.
func NewAttachmentService(attachments AttachmentRepository, tickets Repository) *AttachmentService {
	return &AttachmentService{
		attachments: attachments,
		tickets:     tickets,
		cfg:         DefaultAttachmentConfig(),
	}
}

// SetConfig updates the attachment service configuration.
func (s *AttachmentService) SetConfig(cfg AttachmentConfig) {
	s.cfg = cfg
}

// validateFileSize checks that the file data does not exceed the configured
// maximum size.
func (s *AttachmentService) validateFileSize(data []byte) error {
	if s.cfg.MaxFileSize > 0 && int64(len(data)) > s.cfg.MaxFileSize {
		return fmt.Errorf("%w: maximum is %d bytes, got %d bytes", ErrFileTooLarge, s.cfg.MaxFileSize, len(data))
	}
	return nil
}

// validateContentType checks that the declared content type is in the whitelist.
func validateContentType(declaredType string) bool {
	ct := strings.TrimSpace(declaredType)
	if idx := strings.Index(ct, ";"); idx >= 0 {
		ct = ct[:idx]
	}
	ct = strings.ToLower(strings.TrimSpace(ct))
	return allowedContentTypes[ct]
}

// sanitizeFilename removes path components and replaces special characters
// to prevent directory traversal and ensure safe filenames.
func sanitizeFilename(filename string) string {
	if filename == "" {
		return ""
	}
	// Strip any path components — keep only the base name
	name := filepath.Base(filename)
	// Replace any character that is not a word char, dot, or hyphen
	name = specialCharRegex.ReplaceAllString(name, "_")
	// Collapse multiple underscores
	name = multiUnderscoreRegex.ReplaceAllString(name, "_")
	// Trim leading/trailing underscores and dots
	name = strings.Trim(name, "_.")
	// Prevent empty after sanitization
	if name == "" {
		name = "upload"
	}
	return name
}

// UploadInput holds the data for uploading an attachment.
type UploadInput struct {
	TenantID    uuid.UUID
	TicketID    uuid.UUID
	UserID      uuid.UUID
	Role        string
	Filename    string
	ContentType string
	FileData    []byte
}

// Upload stores a file attachment on a ticket after verifying access and
// validating file size, content type, and filename.
func (s *AttachmentService) Upload(ctx context.Context, input UploadInput) (*domainTicket.Attachment, error) {
	// Validate filename
	if input.Filename == "" {
		return nil, ErrEmptyFilename
	}

	// Validate file size
	if err := s.validateFileSize(input.FileData); err != nil {
		return nil, err
	}

	// Validate content type against whitelist
	if !validateContentType(input.ContentType) {
		return nil, fmt.Errorf("%w: %s", ErrInvalidContent, input.ContentType)
	}

	// Sanitize filename
	safeFilename := sanitizeFilename(input.Filename)

	// Verify ticket access
	t, err := s.tickets.GetByID(ctx, input.TicketID, input.TenantID)
	if err != nil {
		return nil, err
	}
	if !t.CanBeViewedBy(input.UserID, input.Role) {
		return nil, domainTicket.ErrForbidden
	}

	return s.attachments.Create(ctx, AttachmentUploadInput{
		TicketID:    input.TicketID,
		UserID:      input.UserID,
		Filename:    safeFilename,
		ContentType: input.ContentType,
		FileSize:    int64(len(input.FileData)),
		FileData:    input.FileData,
	})
}

// ListInput holds the parameters for listing attachments.
type ListInput struct {
	TenantID uuid.UUID
	TicketID uuid.UUID
	UserID   uuid.UUID
	Role     string
}

// List returns metadata for all attachments on a ticket after verifying access.
func (s *AttachmentService) List(ctx context.Context, input ListInput) ([]domainTicket.Attachment, error) {
	// Verify ticket access
	t, err := s.tickets.GetByID(ctx, input.TicketID, input.TenantID)
	if err != nil {
		return nil, err
	}
	if !t.CanBeViewedBy(input.UserID, input.Role) {
		return nil, domainTicket.ErrForbidden
	}
	return s.attachments.List(ctx, input.TicketID)
}

// DownloadResult holds the attachment metadata and file content for download.
type DownloadResult struct {
	Attachment *domainTicket.Attachment
	Reader     io.Reader
}

// DownloadInput holds the parameters for downloading an attachment.
type DownloadInput struct {
	TenantID     uuid.UUID
	TicketID     uuid.UUID
	AttachmentID uuid.UUID
	UserID       uuid.UUID
	Role         string
}

// Download returns the attachment metadata and file content after verifying access.
func (s *AttachmentService) Download(ctx context.Context, input DownloadInput) (*domainTicket.Attachment, []byte, error) {
	// Verify ticket access
	t, err := s.tickets.GetByID(ctx, input.TicketID, input.TenantID)
	if err != nil {
		return nil, nil, err
	}
	if !t.CanBeViewedBy(input.UserID, input.Role) {
		return nil, nil, domainTicket.ErrForbidden
	}
	return s.attachments.GetByID(ctx, input.AttachmentID, input.TicketID)
}
