run:
  timeout: 5m
  go: "1.25"
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocyclo
    - misspell
    - revive
linters-settings:
  gocyclo:
    min-complexity: 20
  gosec:
    excludes:
      - G104
