package handler

import (
	"net/http"

	httpSwagger "github.com/swaggo/http-swagger"
)

// SwaggerHandler serves the Swagger UI at /swagger/. The OpenAPI specification
// is generated by `swag init` from the swag annotations in the handler
// package (see auth.go and ticket.go for the main endpoint annotations).
//
// TODO: Wire this handler into the router in server.go (do NOT edit server.go
// from this task — register it with r.Get("/swagger/*", handler.SwaggerHandler())).
func SwaggerHandler() http.Handler {
	return httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"),
	)
}
